global using SupermarketManagement.Entities;
global using SupermarketManagement.UseCases.DataStorePlaginInterfaces;
global using SupermarketManagement.UseCases.ProductsUseCasesInterfaces;
global using SupermarketManagement.UseCases.TransactionsUseCasesInterfaces;
global using SupermarketManagement.UseCases.UseCasesInterfaces;
global using System;
global using System.Collections.Generic;
